adminCredentials:
  user: admin
  password: admin
database:
  driver: org.h2.Driver
  #url: jdbc:h2:tcp://localhost/~/teamspace;
  url: jdbc:h2:file:~/teamspace;
  user: admin
  password: admin
  maxActive: 10
  maxIdle: 5
batch-database:
  driver: org.h2.Driver
  url: jdbc:h2:file:~/teamspace-batch;
  user: admin
  password: admin
  maxActive: 10
  maxIdle: 5